#!/bin/bash
export MAPDIR=~/mapdir

[ -f $MAPDIR/done.txt ] && exit 0

[ -d $MAPDIR/bin ] || mkdir $MAPDIR/bin

if [ ! -f $MAPDIR/planet-latest.osm.pbf ] ; then 
  # Clean up tmp files because we're going to have a newer map
  rm $MAPDIR/*.tmp
  # Force fetching the source and compiling a fresh maptool 
  rm -rf $mapdir/bin/*
  wget http://download.geofabrik.de/europe-latest.osm.pbf -O $MAPDIR/planet-latest.osm.pbf || 
    exit 1
fi

if [ ! -f $MAPDIR/bin/navit/maptool/maptool ] ; then
  git clone https://github.com/mdankov/navit.git ~/navitsrc &&
  cd ~/navitsrc &&
  git checkout maptool-save-state &&
  cd $MAPDIR/bin &&
  cmake ~/navitsrc &&
  make || 
    exit 1
  # tmp files make no sense after maptool rocompilation
  rm $MAPDIR/*.tmp
fi

cd $MAPDIR

if [ -f saved_state_.tmp ] ; then
  export OPTS=-C -I
else
  export OPTS=-I
fi

bin/navit/maptool/maptool $OPTS -k -6 --protobuf -S 2147483648 -i planet-latest.osm.pbf planet.bin
export MAPTOOLRC=$?

if [  $MAPTOOLRC -eq 100 ] ; then
  exit 0
fi
if [ $MAPTOOLRC -eq 0 ] ; then
  touch $MAPDIR/done.txt
  exit 0
else
  exit $MAPTOOLRC
fi
