#!/bin/bash
export MAPDIR=~/mapdir

[ -f $MAPDIR/done.txt ] && exit 0

[ -d $MAPDIR/bin ] || mkdir $MAPDIR/bin

[ -f $MAPDIR/planet-latest.osm.pbf ] || 
  wget http://download.geofabrik.de/europe-latest.osm.pbf -O $MAPDIR/planet-latest.osm.pbf || 
    exit 1

[ -f $MAPDIR/navit/navit/maptool/maptool ] ||
   git clone https://github.com/mdankov/navit.git ~/navitsrc &&
   cd ~/navitsrc &&
   git checkout maptool-save-state &&
   cd $MAPDIR/bin &&
   cmake ~/navitsrc &&
   make || 
    exit 1

cd $MAPDIR

if [ -f saved_state_.tmp] ; then
  export OPTS=-C -I
else
  export OPTS=-I
fi

bin/navit/maptool/maptool $OPTS -k -6 --protobuf -S 2048 -i planet-latest.osm.pbf -o planet.bin
export MAPTOOLRC=$?

if [  $MAPTOOLRC -eq 100 ] ; then
  exit 0
fi
if [ $MAPTOOLRC -eq 0 ] ; then
  touch $MAPDIR/done.txt
  exit 0
else
  exit $MAPTOOLRC
fi
